"""add_reactions_to_messages

Revision ID: 430b27675ca9
Revises: b7c4e2a9f310
Create Date: 2026-02-03 11:31:11.497844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430b27675ca9'
down_revision: Union[str, None] = 'b7c4e2a9f310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('reactions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'reactions')
    # ### end Alembic commands ###
