"""Add status column to messages

Revision ID: 5d148ef19220
Revises: acfde6029ad4
Create Date: 2026-02-03 02:23:44.334980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d148ef19220'
down_revision: Union[str, None] = 'acfde6029ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'status')
    # ### end Alembic commands ###
