"""Add ChatRoomMember model with last_read_at

Revision ID: adefca12d281
Revises: 5d148ef19220
Create Date: 2026-02-03 02:26:13.785241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adefca12d281'
down_revision: Union[str, None] = '5d148ef19220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatroom_member',
    sa.Column('chatroom_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chatroom_id'], ['chatroom.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('chatroom_id', 'user_id')
    )
    op.drop_table('chatroom_members')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatroom_members',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('chatroom_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['chatroom_id'], ['chatroom.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chatroom_id')
    )
    op.drop_table('chatroom_member')
    # ### end Alembic commands ###
